baseURL = "http://sweetlie.today"
languageCode = "fr-FR"
defaultContentLanguage = "fr-fr"
title = "Sweet Code Dream"
theme = "hugo-tranquilpeak-theme"
paginate = 7
canonifyurls = true
googleAnalytics = "UA-96373440-2"

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Sweetlie"
  job = "Codeur, Resto-Drood"
  gravatarEmail = "sweetlie@wipeinc.io"

[[menu.main]]
  weight = 0
  identifier = "Home"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "https://sweetlie.today"

[[menu.main]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/wow-sweetlie"

[[menu.main]]
  weight = 0
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/wowsweetlie"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params.footer]
  copyright = 'Sweetlie selon les termes de la <a rel="license"
  href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons
  Attribution 4.0 International</a>'


[params]
  favicon = "/favicon.png"
  dateFormat = "2 January 2006"
  coverImage = "cover.jpg"
  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  imageGallery = true
  hierarchicalCategories = true
