version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    branches:
      only:
        - master
    working_directory: ~/blog
    environment:
      GIT_DEPLOY_DIR: public
      GIT_DEPLOY_BRANCH: gh-pages
    steps:
      - checkout
      - run: go get -v github.com/spf13/hugo
      - run: hugo
      - run: git config --global user.name "circle-ci"
      - run: git config --global user.email "circle-ci@circle-ci.org"
      - run: wget https://raw.githubusercontent.com/X1011/git-directory-deploy/master/deploy.sh && chmod +x deploy.sh

      - add_ssh_keys:
        fingerprints: "96:84:40:4a:92:1e:e7:72:5e:a9:b6:77:dc:89:96:d1"
      - deploy:
        command: ./deploy.sh



